export const content = {
  "contactSectionTitle": "Contact",
  "contactSectionSubtitle": "Need Junk Gone? Contact J&B's Team",
  "contactSectionDescription": "Strong service, clean results. We handle residential and commercial cleanouts in Tampa and the surrounding area.",
  "quickContactTitle": "Quick Contact",
  "bookPickupTitle": "Book a Pickup",
  "bookPickupDescription": "Fill out the form and we'll call or text to confirm your appointment.",
  "phoneNumber": "813-724-4975",
  "emailAddress": "jdcviper2408@icloud.com",
  "operatingHours": "Operating hours: Mon-Sat 8am-7pm",
  "nameLabel": "Name",
  "phoneLabel": "Phone",
  "emailLabel": "Email",
  "detailsLabel": "Details",
  "sendRequestButton": "Send Request",
  "brandName": "J&B Junk Removal",
  "brandTagline": "Mobile driveway and safe dumpsters",
  "navHome": "Home",
  "navServices": "Services",
  "navAbout": "About",
  "navGallery": "Gallery",
  "navContact": "Contact Us",
  "footerCopyright": "© 2026 J&B Junk Removal. All rights reserved.",
  "gallerySectionTitle": "Our Work",
  "gallerySectionSubtitle": "Recent Projects",
  "gallerySectionDescription": "Real jobs, real results. See how we handle every job with care and professionalism.",
  "galleryAlt1": "J&B Junk Removal crew loading a truck in Tampa, FL",
  "galleryAlt2": "Loaded hauling trailer after a residential junk removal job",
  "galleryAlt3": "Construction debris loaded for removal from a job site",
  "galleryAlt4": "Estate and property cleanout — furniture removed from a home",
  "galleryAlt5": "Brush and yard debris removal from a residential property",
  "galleryAlt6": "Clean driveway after professional junk removal service",
  "heroBadge": "Junk Removal & Hauling — Tampa, FL",
  "heroTitle": "Need Junk Gone Fast? We Haul It All.",
  "heroDescription": "Fast, affordable junk removal and hauling for homes and businesses in Tampa, FL and surrounding communities. You point, we load, we haul it away.",
  "heroFeature1": "Same Day Service",
  "heroFeature2": "Free Estimates",
  "heroFeature3": "We Do the Heavy Lifting",
  "heroCallButton": "Call 813-724-4975",
  "heroTextButton": "Text Us for a Quote",
  "quoteFormBadge": "Free Quote",
  "quoteFormTitle": "Get Your Free Quote",
  "quoteFormDescription": "Tell us what needs to go — we'll get back to you fast.",
  "quoteFormNamePlaceholder": "Your Name",
  "quoteFormPhonePlaceholder": "(555) 555-5555",
  "quoteFormEmailPlaceholder": "your@email.com",
  "quoteFormDetailsPlaceholder": "Describe your project or any details we should know...",
  "quoteFormSubmitButton": "Get My Free Quote",
  "quoteFormCallText": "Prefer to talk?",
  "quoteFormDisclaimer": "By submitting, you agree to receive a call or text for your quote.",
  "serviceAreaTitle": "Junk Removal Near You",
  "serviceAreaSubtitle": "Proudly Serving Tampa & the Surrounding Area.",
  "serviceAreaDescription": "Based in Carrollwood, Tampa, FL, we provide junk removal, property cleanouts, hauling, and more to homeowners, contractors, and businesses across the Tampa Bay area.",
  "serviceAreaAvailability": "Available in most areas — call for availability",
  "communitiesTitle": "Communities We Serve",
  "communityTampa": "Tampa",
  "communityTampaTag": "HQ",
  "communityCarrollwood": "Carrollwood",
  "communityCarrollwoodTag": "HQ",
  "communitySaintPetersburg": "St. Petersburg",
  "communityClearwater": "Clearwater",
  "communityBrandon": "Brandon",
  "communityLutz": "Lutz",
  "communityLandOLakes": "Land O' Lakes",
  "communityWesley Chapel": "Wesley Chapel",
  "communityNew Tampa": "New Tampa",
  "communityPlantCity": "Plant City",
  "communityRiverview": "Riverview",
  "communitiesSurrounding": "+ Surrounding Tampa Bay communities",
  "getQuoteButton": "Get a Free Quote",
  "servicesSectionTitle": "What We Do",
  "servicesSectionSubtitle": "Our Services",
  "servicesSectionDescription": "Junk removal, property cleanouts, hauling, and more for homeowners, contractors and businesses in Tampa, FL.",
  "serviceJunkRemovalTitle": "Junk Removal",
  "serviceJunkRemovalDesc": "Fast, reliable removal of unwanted items from homes, garages, basements, businesses, and properties throughout the Tampa Bay area. We handle the heavy lifting so you don't have to.",
  "serviceEstateCleanoutsTitle": "Estate & Property Cleanouts",
  "serviceEstateCleanoutsDesc": "Complete cleanouts for homes and properties. Whether you're handling an estate, preparing a property for sale, or downsizing, our crew removes everything fast.",
  "serviceConstructionDebrisTitle": "Construction Debris Removal",
  "serviceConstructionDebrisDesc": "Light demolition and construction debris removal for residential projects. From shed teardowns to full renovation cleanups, we haul away debris so your project can move forward.",
  "serviceBrushYardTitle": "Brush & Yard Debris Removal",
  "serviceBrushYardDesc": "Yard and brush cleanup services for homeowners and contractors. We haul away tree limbs, brush piles, yard waste, storm debris, and old fencing.",
  "serviceMaterialHaulingTitle": "Material Hauling",
  "serviceMaterialHaulingDesc": "Transportation and hauling services for bulk landscaping and construction materials. Whether you need materials delivered or hauled away, we've got the capacity.",
  "serviceStorageGarageTitle": "Storage Unit & Garage Cleanouts",
  "serviceStorageGarageDesc": "Quick cleanouts for storage units, garages, sheds, and rental properties. We clear the space fast so it's ready for reuse.",
  "viewAllServicesButton": "View All Services",
  "trustBarLocallyOwned": "Locally Owned & Operated",
  "trustBarLicensed": "Licensed & Insured",
  "trustBarSameDay": "Same Day Service Available",
  "whyChooseUsTitle": "Why Choose Us",
  "whyChooseUsSubtitle": "The J&B Difference.",
  "whyChooseUsDescription": "We're not a franchise or a faceless hauling company. Jose and Brice are local Tampa guys who take every job personally — fast, affordable, and always dependable.",
  "step1Num": "Step 01",
  "step1Title": "Get a Quote",
  "step1Desc": "Call us or request a free quote online.",
  "step2Num": "Step 02",
  "step2Title": "Schedule Pickup",
  "step2Desc": "We arrive on time with a professional crew.",
  "step3Num": "Step 03",
  "step3Title": "We Haul It Away",
  "step3Desc": "You point, we load, we sweep up after.",
  "featureSameDayDesc": "Need it gone today? We offer same-day and next-day junk removal so you're not stuck waiting around.",
  "featureUpfrontPricingDesc": "No hidden fees, no surprise charges. We quote before we start — prices include labor, loading, transportation, and disposal.",
  "featureProfessionalCrewDesc": "Our team handles all the heavy lifting, loading, and hauling. You just point to what needs to go.",
  "featureEcoFriendlyDesc": "We recycle and donate whenever possible. Responsible disposal means less waste in landfills.",
  "featureLicensedInsuredDesc": "Fully licensed and insured for your peace of mind. Residential and commercial projects handled with care.",
  "featureLocallyOwnedDesc": "Based in Carrollwood, Tampa, FL. Jose and Brice live and work in the community they serve — our reputation depends on every job."
};